### ISSUE TITLE
Preparation of example

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/19msmt-distribution#10]
Review existing annotations e.g. https://kbss.felk.cvut.cz/brat/#/19msmt/BlueSky/DA42-POH--has-function/DA42-POH-38.

What needs to be in the example:
- text that can fit on one screen
- use everything from the ontology "FMEA" (i.e. components, failure modes, cause, functions...)
- at least 3 different connected segments of has-component relation (ideally there should at least 2 components that needs to be merged)

------------
Related ontology to annotate:
![image](https://user-images.githubusercontent.com/3962237/172671840-0968d84a-31b6-458c-a7e5-f83f270f19c7.png)

------------
How we will proceed annotations:
1) annotate only concepts
2) annotate separately on [1] one specific relationship
 
We will reference [1] in FTA-FMEA tool.

**Comment by LaChope** [comment]
FI, modified reports are:

- https://kbss.felk.cvut.cz/brat/#/19msmt/BlueSky/DA42-POH--has-function/DA42-POH-39
- https://kbss.felk.cvut.cz/brat/#/19msmt/BlueSky/DA42-POH--has-function/DA42-POH-44

**Comment by blcham** [comment]
done.
