### ISSUE TITLE
Create API for a list of documents and content of document

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/19msmt-distribution#18]
Scenario:
```
GET /documents   // list all documents
```

```
POST /systems/{systemFragment}/documents?documentId=${url}    //imports document into the system
GET  /systems/{systemFragment}
```

@Matthew-Kulich will this API work for you?

**Comment by kostobog** [comment]
pull request for list-document implementation kbss-cvut/fta-fmea#28

**Comment by kostobog** [comment]
pull request for import-documents implementation kbss-cvut/fta-fmea#29

**Comment by blcham** [comment]
@Matthew-Kulich pls, close if completed.
