### ISSUE TITLE
Integrate NLP with FTA-FMEA 

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/19msmt-distribution#2]
- import annotations from one document into a new system or a system selected by the user.
- FTA-FMEA-UI should support the user to navigate to the annotation of a given element

- tasks:
  - create API to extract annotations from BRAT into the git repository (extract annotated files + commit into git)
  - create SPipes API to return "list of documents" from git annotated corpus repository
  - create SPipes API to return the content of the annotated document in a format compatible with FTA/FMEA tool (with references to annotation)
  - create a button to import from the selected document (fta-fmea tool vs. separated application)

**Comment by blcham** [comment]
done
