### ISSUE TITLE
Fix element IRIs generated by convert-document service

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/19msmt-distribution#29]
IRIs of created entities, e.g. components, functions and failure modes should be prefixed by the IRI of type of the entity. For example:
- fta:Component instance - fta:Component/instance-1111

**Comment by kostobog** [comment]
@Matthew-Kulich, can you check if the issue is resolved correctly?

**Comment by Matthew-Kulich** [comment]
Also there's a one more bug with cardinality constraint.
For example when we get this component

```
fta:twin-spars-18  a     fta:Component ;
        fta:hasName      "Should you be more specific ?" , "twin spars" ;
        fta:isPartOf     fta:Empennage-17 ;
        fta:origin       fmea:twin-spars-18 ;
        dc-terms:source  "https://kbss.felk.cvut.cz/brat/#/19msmt/BlueSky/DA42-POH--has-component/DA42-POH-38?focus=T18"

```

**Comment by kostobog** [comment]
This should be already fixed. Try using the newest version of the converter.
The "twin spars" example does not have multiple hasName, see https://kbss.felk.cvut.cz/19msmt-demo/fta-fmea-converter/service?_pId=convert-document

@Matthew-Kulich

**Comment by Matthew-Kulich** [comment]
Yeah I know, I meant if this case can appear in the future, but i guess not. @kostobog
