### ISSUE TITLE
Add selector for annotations in ttl (BK, +?MB)

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/19msmt-distribution#30]

**Comment by kostobog** [comment]
Feature implemented in commit [ce0acd68](https://kbss.felk.cvut.cz/gitblit/commit/19msmt-avic!gate-tools.git/ce0acd689eeb6b8e7a310f2e1223b6c487d2bd1a)

@blcham

**Comment by blcham** [comment]
LGTM
